document.write('<div id="sites">');
document.write('<a href="index.html"><img src="https://cdn-ak.f.st-hatena.com/images/fotolife/d/douga-no-sozaiko/20201217/20201217224419.png" alt="「RightUP」ロゴ" id="footer-main-logo"></a>');
document.write('<div id="footer-sub-logos">');
document.write('<ul>');
document.write('<li class="link-a"><a href="https://douga-no-sozaiko.hateblo.jp/"><img src="https://cdn-ak.f.st-hatena.com/images/fotolife/d/douga-no-sozaiko/20201217/20201217224505.png" alt="「動画の素材庫」ロゴ"></a></li> ');
document.write('</ul>');
document.write('</div>');
document.write('</div>');
document.write('<div id="footer-footer">');
document.write('<ul>');
document.write('<li class="link-a"><a href="use-site.html">サービスのご利用について</a></li>');
document.write('<li class="link-a"><a href="privacy-policy.html">プライバシーポリシー</a></li>');
document.write('<li>Copyright © RightUP. All Rights Reserved.</li>');
document.write('</ul>');
document.write('</div>');
//ページ下Twitterアイコン
document.write('<a href="https://twitter.com/RightUP_group" target="_blank" id="twitter-icon-bottom">');
document.write('<img src="https://cdn-ak.f.st-hatena.com/images/fotolife/d/douga-no-sozaiko/20201231/20201231213540.png">');
document.write('</a>');
//雪降らす開始
document.write('<div class="snowflakes" aria-hidden="true">');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
document.write('<div class="snowflake">');
document.write('❆');
document.write('</div>');
//雪降らす終了
